### ISSUE TITLE
Inventar Computer-Hardware

### ISSUE THREAD

**Issue by Chaozz2go** [cryptic-game/gamedesign#15]
# Description
ein inventar  das  dir anzeigt welche hardware du besitzt (zum z.b. zusammenbauen eines rechners) und wieviel davon diese items die du in deinem inventar hast sollte man in den müll werfen können (für immer weg)
einbauen in einen pc
und an andere user versenden

siehe #30 Control-Center

**Comment by tanneberger** [comment]
backend done

**Comment by Tristan-H11** [comment]
Siehe #30
