### ISSUE TITLE
CPU-Kryptominer-App

### ISSUE THREAD

**Issue by DevMimas** [cryptic-game/gamedesign#31]
# Description
Kryptominer der CPU lastig ist.
Der Miner ist auf dem eigenen Rechner installiert und generiert Morphcoins. Eine kontinuierliche Geldquelle.

**UI**
- aussehen des Miners als Anwendung
- ein Schieberegler von 10% bis 100%
- ein Button zum Starten und Beenden
- Anzeige wieviel Morphcoins generiert werden

**Logik**
- eine Formel die die MC generiert
- mit einbeziehen CPU Frequenz, Kerne und RAM

# Steps
- [x] Check the new gamebit
- [x] Create a concept and write it into the game design document or similar
- [x] Create a miner-formula
- [x] Check the new concept in gamedesign/backend/frontend
- [x] Rework the concept
- [x] Check again
- [x] Finish the gamebit

**Comment by tanneberger** [comment]
Backend Done

**Comment by DevMimas** [comment]
Änderung: Schieberegler ist stufenlos
