### ISSUE TITLE
Hardwareshop-App

### ISSUE THREAD

**Issue by Maulwurf852** [cryptic-game/gamedesign#45]
## Discription
Ein Hardwareshop in Form einer App. Globaler Händler.

## Parts
- [x] Konzept für Logik des Systems, Darstellung, Kaufabwicklung erstellen
- [x] UI-Elemente festlegen zb für den Transfer, Bezahlung
- [x] Spielelement Prüfen
- [x] Überarbeiten
- [x] Fertigstellen

**Comment by tanneberger** [comment]
Backend Done Waiting for Merge ...
