### ISSUE TITLE
Computerhardware

### ISSUE THREAD

**Issue by Chaozz2go** [cryptic-game/gamedesign#5]

**Comment by tanneberger** [comment]
Defelo + Sunti
- Zusammenbauen eines Devices aus verschiedenen Hardware Elementen ( "Realitätsnah")
- Standart PC 
- "Leistung" eine Gerätes -> Resourcen Managment in Cooperation mit Services als verbraucher
   -> Microservice Endpoint wo das abfrag bar ist.
