### ISSUE TITLE
Hardware Gameconfigs

### ISSUE THREAD

**Issue by tanneberger** [cryptic-game/gamedesign#53]
# Description
I send you the config file in the gamedesign channel (discord) pls adjust it ... I want device too be done. @DevMimas @Maulwurf852 

Issues that belong together:
- #5 Hardware
- #7 Start-PC
- #70 Calculation formula for services

## Hardware compatibility
![Hardwarekompatibilität_pre-alpha-2_v4](https://user-images.githubusercontent.com/44207756/77485654-f6b71a00-6e2d-11ea-998b-3d9c70afdfc8.png)

# Steps
Update the files in the backend:
- [x] Update device vars.py (List of all hardware components)
- [x] Update service vars.py (needs value and formula of services)
- [x] Update inventory vars.py (prices of the hardware and the category)
- [x] Check
- [x] Finish

**Comment by DevMimas** [comment]
Done
