### ISSUE TITLE
Start-PC

### ISSUE THREAD

**Issue by Chaozz2go** [cryptic-game/gamedesign#7]
# Description
Ein Computer mit leistungsschwacher Hardware - siehe Issue #53. Dazu gehört:
- Mainboard
- CPU
- RAM
- interne Grafikkarte (OnBoard)
- Festplatte

alle Hardwareteile mit Namen und Leistungsangaben zb CPU Frequenz 800 Mhz

# Additional context
Abstimmung aus Discord 06.10.2019. Zum Spieleintritt ist ein Start-Computer vorhanden. Weitere können zusammengebaut werden.

**Comment by tanneberger** [comment]
Dattito
