### ISSUE TITLE
Verification to support

### ISSUE THREAD

**Issue by Maulwurf852** [cryptic-game/gamedesign#78]
**Is your feature request related to a problem? Please describe.**
Da personenbezogene Daten entfernt wurden, muss eine anderweitige Identifizierung gegenüber dem Support dargestellt werden.

Eine Zurücksetzung des Passwortes über "Passwort vergessen" ist zur Zeit auch nicht möglich.

**Describe the solution you'd like**
Eine Lösung muss noch seperat ausführlich diskutiert werden!!! Es ist ggf. erst ein Supportsystem und ein Admin-Panel zu implementieren.

**Additional Comments**
Bei Fragen wende Dich an @DevMimas oder @Maulwurf852 .

**Comment by JannikEmmerich** [comment]
Wäre es nicht viel sinnvoller (und auch einfacher zu implementieren), wenn man ein Ticketsystem in das Control-Center einbauen würde?
Ein Zurücksetzen des Passworts könnte man auf einer "Passwort vergessen" Seite via Recovery Codes (ähnlich wie bei 2FA) bereitstellen.
